
# Setting PATH for Python 3.2
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.2/bin:${PATH}"
export PATH

##
# Your previous /Users/Justin/.bash_profile file was backed up as /Users/Justin/.bash_profile.macports-saved_2013-06-19_at_16:59:53
##

# MacPorts Installer addition on 2013-06-19_at_16:59:53: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/Justin/.bash_profile file was backed up as /Users/Justin/.bash_profile.macports-saved_2013-09-17_at_14:09:29
##

# MacPorts Installer addition on 2013-09-17_at_14:09:29: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

export CLICOLOR=1
# Dark background
export LSCOLORS=GxFxCxDxBxegedabagaced
# Light background
# export LSCOLORS=ExFxBxDxCxegedabagacad

# ME__________________
# source the .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
